### ISSUE TITLE
implement multiple gene sets

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#386]

**Comment by jingchunzhu** [comment]
I think this is still quite an important issue. And I remember you are saying today that you are just going to lump them together. I think that's a bad idea because here is the problem

- Some geneset like flybase set is not meaningful for any gene expression data
- Some geneset like the 8000 pathways + default gene set is only meaningful for BPA + expression data
- Some geneset like paradigm pathways is only meaningful for PARADIGM + expression data : please note that PARADIGM pathway needs a structured pathway, rather than a bad of genes
all genesets are meaningful for copy number and mutation data.

**Comment by nathandunn** [comment]
okay.  thnaks for the feedback

**Comment by nathandunn** [comment]
- exclusive multiple gene set lists and add different data types

- BPA analysis: BPA score, gene exp, BPA pathway
PARADIGM analysis version 1: PARADIGM pathway score; gene exp. CNV; PARADIGM pathway
PARADIGM analysis version 2: PARADIGM pathway score; IPL; PARADIGM pathway
CNV analysis: CNV pathway score, CNV; 42 pathways
Mutation analysis: m pathway socre, mutation; 42 pathways
CNV + mutation analysis, c+m pathway socre; CNV, mutation; 42 pathways
